box: oraclelinux/9-btrfs
box_url: https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9-btrfs.json
vm_name: ol9_vagrant
mem_size: 4096
cpus: 4
public_ip: 192.168.56.140
disk1_name: ./ol9_19_u01.vdi
disk2_name: ./ol9_19_u02.vdi
non_rotational: "on"
disk_size: 100
